us_cities = [
    'New York, New York', 
    'Los Angeles, California', 
    'Chicago, Illinois', 
    'Houston, Texas',
    'Phoenix, Arizona',
    'Philadelphia, Pennsylvania',
    'San Antonio, Texas',
    'San Diego, California',
    'Dallas, Texas',
    'Austin, Texas',
    'Jacksonville, Florida',
    'San Jose, California',
    'Fort Worth, Texas',
    'Columbus, Ohio',
    'Charlotte, North Carolina',
    'Indianapolis, Indiana',
    'San Francisco, California',
    'Seattle, Washington',
    'Denver, Colorado',
    'Oklahoma City, Oklahoma',
    'Nashville, Tennessee',
    'El Paso, Texas',
    'Washington, District of Columbia', 
    'Las Vegas, Nevada',
    'Boston, Massachusetts',
    'Portland, Oregon',
    'Louisville, Kentucky',
    'Memphis, Tennessee',
    'Detroit, Michigan',
    'Baltimore, Maryland',
    'Milwaukee, Wisconsin',
    'Albuquerque, New Mexico',
    'Tucson, Arizona',
    'Fresno, California',
    'Sacramento, California',
    'Mesa, Arizona',
    'Kansas City, Missouri',
    'Atlanta, Georgia',
    'Colorado Springs, Colorado',
    'Omaha, Nebraska',
    'Raleigh, North Carolina',
    'Virginia Beach, Virginia',
    'Long Beach, California',
    'Miami, Florida',
    'Oakland, California',
    'Minneapolis, Minnesota',
    'Tulsa, Oklahoma',
    'Bakersfield, California',
    'Tampa, Florida',
    'Wichita, Kansas'
]