us_cities = [
    'New York, NY', 
    'Los Angeles, CA', 
    'Chicago, IL', 
    'Houston, TX',
    'Phoenix, AZ',
    'Philadelphia, PA',
    'San Antonio, TX',
    'San Diego, CA',
    'Dallas, TX',
    'Austin, TX',
    'Jacksonville, FL',
    'San Jose, CA',
    'Fort Worth, TX',
    'Columbus, OH',
    'Charlotte, NC',
    'Indianapolis, IN',
    'San Francisco, CA',
    'Seattle, WA',
    'Denver, CO',
    'Oklahoma City, OK',
    'Nashville, TN',
    'El Paso, TX',
    'Washington, D.C.', 
    'Las Vegas, NV',
    'Boston, MA',
    'Portland, OR',
    'Louisville, KY',
    'Memphis, TN',
    'Detroit, MI',
    'Baltimore, MD',
    'Milwaukee, WI',
    'Albuquerque, NM',
    'Tucson, AZ',
    'Fresno, CA',
    'Sacramento, CA',
    'Mesa, AZ',
    'Kansas City, MO',
    'Atlanta, GA',
    'Colorado Springs, CO',
    'Omaha, NE',
    'Raleigh, NC',
    'Virginia Beach, VA',
    'Long Beach, CA',
    'Miami, FL',
    'Oakland, CA',
    'Minneapolis, MN',
    'Tulsa, OK',
    'Bakersfield, CA',
    'Tampa, FL',
    'Wichita, KS'
]